version: '3'

services:
  redis:
    image: redis:latest
  db:
    build: ./pattern-db
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
  backend:
    build: ./laravel
    ports:
      - 8000:80
    depends_on:
      - db
      - redis
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: sctr
      DB_USERNAME: root
      DB_PASSWORD: fstr_hrdr_sctr
      CACHE_DRIVER: redis
      REDIS_CLIENT: predis
      REDIS_HOST: redis
      REDIS_PORT: 6379
