version: '3'

services:
  db:
    build: ./pattern-db
  backend:
    build: ./laravel
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: sctr
      DB_USERNAME: root
      DB_PASSWORD: fstr_hrdr_sctr
