version: 2

# based on https://circleci.com/blog/build-a-ci-powered-restful-api-with-laravel/

jobs:
  build:
    docker:
      - image: circleci/php:8.0.11-node-browsers

    working_directory: ~/pattern-backend/laravel
    steps:
      - checkout:
          path: ~/pattern-backend
      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Create Environment file and generate app key"
          command: |
            mv .env.testing .env
            php artisan key:generate
      - run:
          name: "Create database and run migration"
          command: |
            touch database/database.sqlite
            php artisan migrate --env=testing
      - run:
          name: "Run Tests"
          command: ./vendor/bin/phpunit
